CREATE TABLE IF NOT EXISTS USER (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USERNAME TEXT UNIQUE NOT NULL,
    EMAIL TEXT UNIQUE NOT NULL,
    PASSWORD TEXT NOT NULL,
    AMOR_PROPRIO INTEGER DEFAULT 4,
    LAGRIMAS INTEGER DEFAULT 60
);

CREATE TABLE IF NOT EXISTS SLOT (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    NUMERO INTEGER NOT NULL,
    ESTADO TEXT DEFAULT 'vazio',
    TIPO TEXT,
    ETAPA INTEGER DEFAULT 0,
    CONSTRUCAO_FIM TEXT,
    TAREFA_FIM TEXT,
    TAREFA_NOME TEXT,
    TAREFA_CORRETA INTEGER DEFAULT 0,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

CREATE TABLE IF NOT EXISTS HISTORICO (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    TEXTO TEXT NOT NULL,
    CREATED_AT TEXT DEFAULT (datetime('now')),
    FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);
